Allow email customization
Cal-CS-61A-Staff/examtool pull request #10
Opened 2020-05-15 21:20 UTC by chrononyan

Email body should have at least `exam` to prevent confusion (added `course` because why not)

2020-05-18 18:43 UTC, ThaumicMekanism requested changes
You also need to bump the version. There is also #12 open so be aware of that (should hopefully land soon).

2020-05-18 18:43 UTC, ThaumicMekanism commented on examtool/cli/send.py
> +    show_default=True
nit: trailing comma

2020-05-18 18:43 UTC, ThaumicMekanism commented on examtool/cli/send.py
> +    show_default=True
nit: trailing comma

2020-05-19 01:28 UTC, chrononyan commented
This is why version bumps should not be done in PRs

2020-05-20 16:34 UTC, merged